### ISSUE TITLE
Crash when

### ISSUE THREAD

**Issue by Kilowog01** [DK22Pac/v2saconv#2]
Some files crash the converter
When i open the players parts the program crash.
Example of one file that crash the converter:
OpenIV/GTA V/x64v.rpf/models/streamedpeds_players.rpf/player_one/head_000_r.ydd

But all parts (or a least the parts that i tried to convert) of the 3 players crashs

**Comment by 50thomatoes50** [comment]
I think it's the same issue #1

**Comment by Kilowog01** [comment]
What should I do with it? It's impossible to compile because is full of errors, update the link to the executable please

**Comment by DK22Pac** [comment]
The crash doesn't happen for me with https://github.com/DK22Pac/v2saconv/commit/4afec26eebc068c59ffb59fc94b990b74d3aab9a
![Image](http://i.imgur.com/ch2xFgj.png)
Please try the new version and report if a crash still happen for you.

**Comment by Kilowog01** [comment]
The problem is over, thank you, you're the best! <3
Just one more thing. It's not exactly a problem, because it is easy to bypass but the Smartscreen filter gave me a warning when I started the executable. I do not know, it's something stupid but maybe you can do something...

**Comment by DK22Pac** [comment]
I'm not sure why does this happen.
Thanks for your feedback.
