### ISSUE TITLE
.ytd file converting to .dff

### ISSUE THREAD

**Issue by killerbeee** [DK22Pac/v2saconv#3]
Hi i'm using the converter to convert a ytd file to .dff. However it converts the file to .txd file. Is there any way to convert to a dff instead ?

**Comment by DK22Pac** [comment]
Y**TD** stands for a **T**exture **D**ictionary file format.

**Comment by killerbeee** [comment]
Hi 
Thanks for the reply, you'll have to forgive my ignorance here as new to this. What i'm trying to do is convert the ytd into a dff so it can be opened in Blender.

**Comment by DK22Pac** [comment]
You can not convert texture archive to model file.

**Comment by killerbeee** [comment]
Sorry yes you're right , my fault :) . I just tried a few yft files. Which i assume are the model files. However when putting them through the converter. the converter crashes . 

Thanks again for your help.

**Comment by DK22Pac** [comment]
Y**TD** are **T**exture **D**ictionaries (texture archives)
Y**DR** are **Dr**awables (models)
Y**DD** are **D**rawable **D**ictionaries (model archives)
Y**FT** are **F**ragment **T**ypes (complex models, such as vehicles or animated models)

**Comment by killerbeee** [comment]
Yes so the YFT should work in the converter yes ?

**Comment by DK22Pac** [comment]
Yes.
What are these yft files? Are they original or custom-made?

**Comment by killerbeee** [comment]
originals, problem I have, is that i put the file in the same folder as the converter. Run  the converter, the converter finds the file ok but then it just hangs.

**Comment by killerbeee** [comment]
Hi  I've downloaded a fresh copy of the converter. This has now converted a stock model successfully.  I have now tried a moded model that works fine in game. However this one crashed. So the next question is; is there anything i need to add or remove from the file to get this to work?
